### PR TITLE
Fixes single-page-app support

### PR DESCRIPTION
**Pull request by c4milo**

### CODE REVIEW

**Comment by c4milo** [comment]
@cloudhead ping. This is one is going to take you 5 secs to review :)

**Comment by FruitieX** [comment]
Oops, almost opened an identical pull request, but luckily found this one. Anyway here's what this PR fixes:

Current behaviour (SPA mode):

* GET /foo/bar => Serve file `/foo/bar`
* GET /foo.js => Serve file `/index.html`

Expected behaviour (SPA mode):

* GET /foo/bar => Serve file `/index.html`
* GET /foo.js => Serve file `/foo.js`

Please merge, as SPA mode is broken with this typo in place. :)

**Comment by jaydeep17** [comment]
When is this going live on npm ?

**Comment by cloudhead** [comment]
Done.

**Pull request merged**
