### PR TITLE
Rebase recent Git history

### PR DESCRIPTION
**Pull request by Zarel**
@cloudhead mentioned in #224 that he had trouble cleaning the Git history because of all the merges. This tree converts all merges since brettz9 took over into squashes and rebases, for a linear commit history for all commits since 83aac2e.

The way I did this was by repeatedly running `git rebase -i --rebase-merges 83aac2e`. Trying to convert merges into squashes/rebases from earliest to latest led to merge conflicts, but converting them from latest to earliest was possible with no conflicts.

You should be able to use my rebases:

```
git checkout -b zarel-master master
git pull https://github.com/Zarel/node-static.git zarel-master
git checkout master
git reset --hard 6efac07ba8c01
```

### CODE REVIEW

**Comment by brettz9** [comment]
Because I had not been feeling well at the time you made these updates, I had forgotten about your work on this, so continued forward with some rebases upon resuming work on the project. However, in looking at your work, I was unclear about your information on `git rebase -i --rebase-merges 83aac2e` (that did nothing for me).

My own approach to avoid the conflicts was to graft in new commits with the same contents in place of the merge commits (though referencing the original merge info in the commit messages). This did cause loss of commit author information within a handful of commits, but credits are listed in the changes file, and again, the commits do reference the merge info. For some reason I am unable to load your repo.

If it's ok, @cloudhead , I can force `master` to use this history which amends my changes in this fashion (and which amends the messages per semantic-release-friendly conventions).

**Comment by cloudhead** [comment]
That's fine by me! The only thing I'd like fixed as well is the formatting of the commit messages: some commits eg. 
d12cfb9 have a `-` in frong, eg. `- Docs: give credits`, and should be changed to `docs: give credits`.

**Comment by brettz9** [comment]
@cloudhead Cool. I've applied to `master` what I currently have, so closing here.

There are only a few `Ignore: ` messages that don't follow the normal convention (though no hyphen prefixing them) which I did since those commits only related to my having then switched to my own scoped package namespace or reverting back (i.e., noise of no interest for users of your package). If you want these changed to `chore:` I could do that too as you prefer.

**Comment by brettz9** [comment]
@cloudhead : Any chance we can get a release now? Thanks!

**Pull request closed without merging**
