### PR TITLE
handle 206 status

### LINKED ISSUE #241: [ERR_HTTP_HEADERS_SENT] after successfully requesting a file with "Range:  bytes=0-"
The  `[ERR_HTTP_HEADERS_SENT]` error happens no matter how much or how little I add or remove to my code.

even just the basic server,
```
var ns = new (require('node-static')).Server('./pub');
httpserver = require('http').createServer((req, res)=>{
     req.addListener('end',()=>{
      ns.serve(req, res);
    }).resume();
});
httpserver.listen(1111);
```
as given from the documentation. For some reason, it only affects a specific file; And by specific file, I mean a file which happens to, for some reason, be requested with a `Range: bytes=0-` header.
```
node:_http_server:342
    throw new ERR_HTTP_HEADERS_SENT('write');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.writeHead (node:_http_server:342:11)
    at Server.finish (/home/user/project/node_modules/node-static/lib/node-static.js:125:17)
    at finish (/home/user/project/node_modules/node-static/lib/node-static.js:170:14)
    at /home/user/project/node_modules/node-static/lib/node-static.js:337:13
    at streamFile (/home/user/project/node_modules/node-static/lib/node-static.js:382:13)
    at ReadStream.<anonymous> (/home/user/project/node_modules/node-static/lib/node-static.js:375:17)
    at ReadStream.emit (node:events:511:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
  }
```
This has always worked up until a few days ago, which I guess is more likely my browsers fault.

and after some minor research, it appears that on that specific file, my browser is sending a `Range: bytes=0-` header. When I make a request to that same file, without the header present, it does not cause node-static to error out on me.

According to [an official chromium contributor](https://groups.google.com/a/chromium.org/g/net-dev/c/hYiP5m0K7ZE/m/_EKNxtXiAgAJ), <sub>and I suppose [RFC 7233 §2.1](https://www.rfc-editor.org/rfc/rfc7233#section-2.1),</sub> this is a normal, valid, and considerably probable request, despite the redundant header, that an HTTP server should be able to withstand. It is simply sent to verify that the server supports `Range` headers.

Node.js: v20.3.0
NPM: v9.7.1
node-static: 0.7.11
running OS: Debian 11 (Crostini Linux VM on Chrome OS)
Host OS (and browser): Chrome 115.0.5790.30 Beta

### PR DESCRIPTION
**Pull request by zkrige**
resolves #241

### CODE REVIEW

**Comment by zkrige** [comment]
I'm not sure about this. The latest npm repository has code from 0.7.9 in it, but it lists the version as 0.7.11

**Comment by brettz9** [comment]
Thanks for the fix, but this PR has way too many changes.

1. The diffs should be against the current version in `master`, not against the version in npm. There have been many changes since the npm version (whether or not @cloudhead will find the time to publish is another issue) so that is why you are seeing a different codebase.

2. There should be no changes to whitespace, etc. unless called for by our ESLint rules. Just the changes relevant for the fix.

Thanks!

**Comment by EdricCantu** [comment]
@zkrige, A lot of the code has changed in this pull, and that alone makes it harder to track the significant change. 





If i may ask, **is** the only significant change the added `&& status !== 206`condition in Server.prototype.finish?

If so, you can just narrow down the change to that line only, unless there's something I'm missing, which I most definitely am. I'm having a hard time understanding the code, unchanged as it is, and forever I will question the usage and function of `Response.writeHead`.

**Comment by zkrige** [comment]
@EdricCantu apologies for the noise. I'll reject this PR and create a new one.

The reason for the `&& status !== 206` condition is as follows:

when there is a byte range, the server returns a 206 code, but it writes out the headers BEFORE this block is reached. Writing out the headers again in this block causes this exception

   throw new ERR_HTTP_HEADERS_SENT('write');

**Pull request closed without merging**
