### PR TITLE
Remove unused Buffer creation

### PR DESCRIPTION
**Pull request by cloudhead**
Fixes an issue with large files.

### CODE REVIEW

**Comment by jozsi** [comment]
```
jozsi@lfa:~/www$ npm install cloudhead/node-static#remove-buffer
node-static@0.7.7 node_modules/node-static
├── mime@1.3.4
├── colors@1.1.2
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
jozsi@lfa:~/www$ ./node_modules/node-static/bin/cli.js -p 8888 -a 0.0.0.0
serving "." at http://0.0.0.0:8888
/home/jozsi/www/node_modules/node-static/lib/node-static.js:376
                    chunk.copy(buffer, offset);
                          ^

TypeError: argument should be a Buffer
    at TypeError (native)
    at ReadStream.<anonymous> (/home/jozsi/www/node_modules/node-static/lib/node-static.js:376:27)
    at emitOne (events.js:82:20)
    at ReadStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at onread (fs.js:1739:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)
```

**Comment by cloudhead** [comment]
@jozsi thanks, had forgotten one usage of the variable. (I can't test it currently)

**Comment by jozsi** [comment]
It works now, thanks. :+1: 

Note: it took a few seconds till the download of the big file started, however it might've been a network latency issue - I wasn't able to reproduce it on the same file after.

**Comment by cloudhead** [comment]
Thanks for testing it out.

**Pull request merged**
